// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCGhg4Xk8pfGqOfSL5XL9JrnM9R-iYoUto',
//     appId: '1:248324705249:web:d93cc8029e760e244120a0',
//     messagingSenderId: '248324705249',
//     projectId: 'fq-olp',
//     authDomain: 'fq-olp.firebaseapp.com',
//     storageBucket: 'fq-olp.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDJcQEAqHh2nFpgpUt5worqzvceUoxVXPo',
//     appId: '1:248324705249:android:8b8522fb19dbde064120a0',
//     messagingSenderId: '248324705249',
//     projectId: 'fq-olp',
//     storageBucket: 'fq-olp.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDwmUo2R1J3SeiGMPHuV6qA-L4xzWWYtVw',
//     appId: '1:248324705249:ios:5cd16e8e95606f2b4120a0',
//     messagingSenderId: '248324705249',
//     projectId: 'fq-olp',
//     storageBucket: 'fq-olp.appspot.com',
//     iosClientId:
//         '248324705249-vbno003i0h7a0psoq74o3g79kue5vinv.apps.googleusercontent.com',
//     iosBundleId: 'com.example.myquizapp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDwmUo2R1J3SeiGMPHuV6qA-L4xzWWYtVw',
//     appId: '1:248324705249:ios:5cd16e8e95606f2b4120a0',
//     messagingSenderId: '248324705249',
//     projectId: 'fq-olp',
//     storageBucket: 'fq-olp.appspot.com',
//     iosClientId:
//         '248324705249-vbno003i0h7a0psoq74o3g79kue5vinv.apps.googleusercontent.com',
//     iosBundleId: 'com.example.myquizapp',
//   );
// }
